//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyCompany("scene316")]
[assembly: AssemblyProduct("Cake.HipChat")]
[assembly: AssemblyVersion("0.0.2")]
[assembly: AssemblyFileVersion("0.0.2")]
[assembly: AssemblyInformationalVersion("0.0.2")]
[assembly: AssemblyCopyright("Copyright � scene316 2016")]
[assembly: CLSCompliant(true)]

